defmodule Churchapp.Repo.Migrations.CreateReportTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:report_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :resource_key, :text, null: false
      add :filter_params, :map, default: %{}
      add :sort_by, :text
      add :sort_dir, :text, default: "asc"
      add :is_shared, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "report_templates_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:report_templates, [:name, :created_by_id, :resource_key],
             name: "report_templates_unique_name_per_user_resource_index"
           )

    drop_if_exists unique_index(:events, [:title, :start_time], name: "events_unique_event_index")

    alter table(:contributions) do
      modify :notes, :text, null: false
    end
  end

  def down do
    alter table(:contributions) do
      modify :notes, :text, null: true
    end

    create unique_index(:events, [:title, :start_time], name: "events_unique_event_index")

    drop_if_exists unique_index(:report_templates, [:name, :created_by_id, :resource_key],
                     name: "report_templates_unique_name_per_user_resource_index"
                   )

    drop constraint(:report_templates, "report_templates_created_by_id_fkey")

    drop table(:report_templates)
  end
end
