defmodule Churchapp.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:contributions) do
      modify :contribution_date, :utc_datetime_usec,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:contributions) do
      modify :contribution_date, :date, default: fragment("CURRENT_DATE")
    end
  end
end
