defmodule Churchapp.Repo.Migrations.RevertEventTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:events), :event_type_id, to: :event_type

    drop constraint(:events, "events_event_type_id_fkey")

    alter table(:events) do
      modify :event_type, :text, default: "service"
    end
  end

  def down do
    alter table(:events) do
      modify :event_type,
             references(:event_types,
               column: :id,
               name: "events_event_type_id_fkey",
               type: :uuid,
               prefix: "public"
             ), default: nil
    end

    rename table(:events), :event_type, to: :event_type_id
  end
end
