defmodule Churchapp.Repo.Migrations.AddMinistryFunds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ministry_funds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ministry_name, :text, null: false
      add :transaction_type, :text, null: false
      add :amount, :decimal, null: false, precision: 10, scale: 2

      add :transaction_date, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :notes, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # Add check constraint for transaction_type
    create constraint(:ministry_funds, :ministry_funds_transaction_type_check,
             check: "transaction_type IN ('revenue', 'expense')"
           )

    # Add check constraint for amount (must be non-negative)
    create constraint(:ministry_funds, :ministry_funds_amount_check, check: "amount >= 0")

    # Add indexes for common queries
    create index(:ministry_funds, [:ministry_name])
    create index(:ministry_funds, [:transaction_date])
    create index(:ministry_funds, [:transaction_type])
    create index(:ministry_funds, [:ministry_name, :transaction_date])
  end

  def down do
    drop table(:ministry_funds)
  end
end
