defmodule Churchapp.Repo.Migrations.CreateEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :start_time, :utc_datetime, null: false
      add :end_time, :utc_datetime, null: false
      add :all_day, :boolean, null: false, default: false
      add :location, :text
      add :color, :text
      add :is_recurring, :boolean, null: false, default: false
      add :recurrence_rule, :text
      add :recurrence_end_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:events, [:title, :start_time], name: "events_unique_event_index")
  end

  def down do
    drop_if_exists unique_index(:events, [:title, :start_time], name: "events_unique_event_index")

    drop table(:events)
  end
end
