defmodule Churchapp.Repo.Migrations.AddContributions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contributions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :contribution_type, :text, null: false
      add :revenue, :decimal, precision: 10, scale: 2, null: false
      add :notes, :text
      add :contribution_date, :date, null: false, default: fragment("CURRENT_DATE")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :congregant_id,
          references(:congregants,
            column: :id,
            name: "contributions_congregant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:contributions, "contributions_congregant_id_fkey")

    drop table(:contributions)
  end
end
