defmodule Churchapp.Repo.Migrations.AddUserRolesAndPermissions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, null: false, default: "member"
      add :permissions, {:array, :text}, default: []
    end

    alter table(:contributions) do
      modify :contribution_date, :utc_datetime_usec,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:contributions) do
      modify :contribution_date, :date, default: fragment("CURRENT_DATE")
    end

    alter table(:users) do
      remove :permissions
      remove :role
    end
  end
end
