defmodule Churchapp.Repo.Migrations.CreateWeekEndingReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:week_ending_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :week_start_date, :date, null: false
      add :week_end_date, :date, null: false
      add :report_name, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:report_category_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false, default: "0", precision: 10, scale: 2

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :week_ending_report_id,
          references(:week_ending_reports,
            column: :id,
            name: "report_category_entries_week_ending_report_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :report_category_id, :uuid, null: false
    end

    create table(:report_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:report_category_entries) do
      modify :report_category_id,
             references(:report_categories,
               column: :id,
               name: "report_category_entries_report_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create unique_index(:report_category_entries, [:week_ending_report_id, :report_category_id],
             name: "report_category_entries_unique_category_per_report_index"
           )

    alter table(:report_categories) do
      add :name, :text, null: false
      add :display_name, :text, null: false
      add :group, :text, null: false, default: "custom"
      add :sort_order, :bigint, null: false, default: 0
      add :is_default, :boolean, null: false, default: false
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:report_categories, [:name], name: "report_categories_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:report_categories, [:name],
                     name: "report_categories_unique_name_index"
                   )

    alter table(:report_categories) do
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :is_default
      remove :sort_order
      remove :group
      remove :display_name
      remove :name
    end

    drop_if_exists unique_index(
                     :report_category_entries,
                     [:week_ending_report_id, :report_category_id],
                     name: "report_category_entries_unique_category_per_report_index"
                   )

    drop constraint(:report_category_entries, "report_category_entries_report_category_id_fkey")

    alter table(:report_category_entries) do
      modify :report_category_id, :uuid
    end

    drop table(:report_categories)

    drop constraint(
           :report_category_entries,
           "report_category_entries_week_ending_report_id_fkey"
         )

    drop table(:report_category_entries)

    drop table(:week_ending_reports)
  end
end
