defmodule Churchapp.Repo.Migrations.RemoveEventTypeField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      remove :event_type
    end
  end

  def down do
    alter table(:events) do
      add :event_type, :text, null: false, default: "service"
    end
  end
end
