defmodule Churchapp.Repo.Migrations.AddCongregants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:congregants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :member_id, :bigint
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :gender, :text
      add :address, :text
      add :city, :text
      add :state, :text
      add :suite, :text
      add :zip_code, :text
      add :country, :text
      add :mobile_tel, :text
      add :home_tel, :text
      add :work_tel, :text
      add :dob, :date
      add :member_since, :date, default: fragment("CURRENT_DATE")
      add :status, :text, null: false, default: "member"
      add :is_leader, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:congregants, [:member_id], name: "congregants_unique_member_id_index")
  end

  def down do
    drop_if_exists unique_index(:congregants, [:member_id],
                     name: "congregants_unique_member_id_index"
                   )

    drop table(:congregants)
  end
end
