defmodule Churchapp.Repo.Migrations.RemoveEventUniqueness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:events, [:title, :start_time], name: "events_unique_event_index")
  end

  def down do
    create unique_index(:events, [:title, :start_time], name: "events_unique_event_index")
  end
end
