defmodule Churchapp.Repo.Migrations.AddImageToCongregants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:congregants) do
      add :image, :text
    end
  end

  def down do
    alter table(:congregants) do
      remove :image
    end
  end
end
