defmodule Churchapp.Repo.Migrations.CreateAttendanceModule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:attendance_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_datetime, :utc_datetime, null: false
      add :notes, :text
      add :total_present, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id, :uuid, null: false
    end

    create table(:attendance_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :present, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:attendance_sessions,
            column: :id,
            name: "attendance_records_session_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :congregant_id,
          references(:congregants,
            column: :id,
            name: "attendance_records_congregant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:attendance_records, [:session_id, :congregant_id],
             name: "attendance_records_unique_session_congregant_index"
           )

    create table(:attendance_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:attendance_sessions) do
      modify :category_id,
             references(:attendance_categories,
               column: :id,
               name: "attendance_sessions_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:attendance_categories) do
      add :name, :text, null: false
      add :description, :text
      add :color, :text, null: false, default: "#06b6d4"
      add :active, :boolean, null: false, default: true
      add :is_system, :boolean, null: false, default: false
      add :display_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:attendance_categories, [:name],
             name: "attendance_categories_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:attendance_categories, [:name],
                     name: "attendance_categories_unique_name_index"
                   )

    alter table(:attendance_categories) do
      remove :updated_at
      remove :inserted_at
      remove :display_order
      remove :is_system
      remove :active
      remove :color
      remove :description
      remove :name
    end

    drop constraint(:attendance_sessions, "attendance_sessions_category_id_fkey")

    alter table(:attendance_sessions) do
      modify :category_id, :uuid
    end

    drop table(:attendance_categories)

    drop_if_exists unique_index(:attendance_records, [:session_id, :congregant_id],
                     name: "attendance_records_unique_session_congregant_index"
                   )

    drop constraint(:attendance_records, "attendance_records_session_id_fkey")

    drop constraint(:attendance_records, "attendance_records_congregant_id_fkey")

    drop table(:attendance_records)

    drop table(:attendance_sessions)
  end
end
