defmodule Churchapp.Repo.Migrations.AddRequiredFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Update existing NULL values to empty strings before adding NOT NULL constraint
    execute "UPDATE congregants SET address = '' WHERE address IS NULL"
    execute "UPDATE congregants SET city = '' WHERE city IS NULL"
    execute "UPDATE congregants SET state = '' WHERE state IS NULL"
    execute "UPDATE congregants SET zip_code = '' WHERE zip_code IS NULL"
    execute "UPDATE congregants SET mobile_tel = '' WHERE mobile_tel IS NULL"

    alter table(:congregants) do
      modify :mobile_tel, :text, null: false
      modify :zip_code, :text, null: false
      modify :state, :text, null: false
      modify :city, :text, null: false
      modify :address, :text, null: false
      modify :member_id, :bigint, null: false
    end
  end

  def down do
    alter table(:congregants) do
      modify :member_id, :bigint, null: true
      modify :address, :text, null: true
      modify :city, :text, null: true
      modify :state, :text, null: true
      modify :zip_code, :text, null: true
      modify :mobile_tel, :text, null: true
    end
  end
end
