defmodule Churchapp.Repo.Migrations.AddFamilyRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:family_relationships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :congregant_id,
          references(:congregants,
            column: :id,
            name: "family_relationships_congregant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :related_congregant_id,
          references(:congregants,
            column: :id,
            name: "family_relationships_related_congregant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :family_relationship_type_id, :uuid, null: false
    end

    create table(:family_relationship_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:family_relationships) do
      modify :family_relationship_type_id,
             references(:family_relationship_types,
               column: :id,
               name: "family_relationships_family_relationship_type_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create unique_index(
             :family_relationships,
             [:congregant_id, :related_congregant_id, :family_relationship_type_id],
             name: "family_relationships_unique_relationship_index"
           )

    alter table(:family_relationship_types) do
      add :name, :text, null: false
      add :display_name, :text, null: false
      add :inverse_name, :text
      add :sort_order, :bigint, null: false, default: 0
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:family_relationship_types, [:name],
             name: "family_relationship_types_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:family_relationship_types, [:name],
                     name: "family_relationship_types_unique_name_index"
                   )

    alter table(:family_relationship_types) do
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :sort_order
      remove :inverse_name
      remove :display_name
      remove :name
    end

    drop_if_exists unique_index(
                     :family_relationships,
                     [:congregant_id, :related_congregant_id, :family_relationship_type_id],
                     name: "family_relationships_unique_relationship_index"
                   )

    drop constraint(
           :family_relationships,
           "family_relationships_family_relationship_type_id_fkey"
         )

    alter table(:family_relationships) do
      modify :family_relationship_type_id, :uuid
    end

    drop table(:family_relationship_types)

    drop constraint(:family_relationships, "family_relationships_congregant_id_fkey")

    drop constraint(:family_relationships, "family_relationships_related_congregant_id_fkey")

    drop table(:family_relationships)
  end
end
